### ISSUE TITLE
L1 IDC plotter on Mac

### ISSUE THREAD

**Issue by sameb112** [aprovechodotorg/Data-Processing-Software#82]
![Screenshot 2024-11-15 at 12 06 27 PM](https://github.com/user-attachments/assets/148ab270-3434-4982-9ebb-a0a5d3246212)
 where is the button to reprocess the plot?

**Comment by jaden-berger** [comment]
@sameb112 Please try this branch and see if the ok button shows up

**Comment by sameb112** [comment]
I still don't see the button in the IDC version

<img width="1792" alt="Screenshot 2024-11-21 at 3 16 02 PM" src="https://github.com/user-attachments/assets/83c497e5-d435-4118-9228-7cf85a2a9e24">
<img width="1792" alt="Screenshot 2024-11-21 at 3 14 07 PM" src="https://github.com/user-attachments/assets/64a9d0d1-9255-4910-b063-7dac8865a4ae">

**Comment by jaden-berger** [comment]
How about now?

**Comment by sameb112** [comment]
awesome!
